### ISSUE TITLE
Copying data directly out of FireCloud tables also copies nonprintable characters

### ISSUE THREAD

**Issue by helgridly** [DataBiosphere/firecloud-app#110]
I ran a workflow which produced a bam as output and then copied the path to it by highlighting and hitting Ctrl+C from the workflow details page:

![image.png](https://images.zenhubusercontent.com/5a551950a016c5b034bcc1f3/10e6f94b-d95e-4ad4-aa17-76bf955811f4)

This gives me the text with some extra helpful "this text is left-to-right" nonprintable characters. As displayed in vi:

![image.png](https://images.zenhubusercontent.com/5a551950a016c5b034bcc1f3/22c9be6d-bf70-4d19-9f0e-02bc20aad8b3)

This tripped me up and made me lose a bunch of time when my tools were insisting my bams didn't exist.

I confirmed this happens if I copy out of the main Data tab table too. But it only seems to happen with gs:// links; I can copy sample names and references to participants fine.

------

Test cases to consider:
1. when a gs:// or dos:// url is wider than the table cell, do we show the right-hand side of the value with an ellipses on the left?
2. when you resize the table cell, does the value expand to fill the available space and drop the ellipses once the cell is wide enough?
3. if the raw value has a trailing quote, does the quote remain at the end? Example: `gs://my-long-bucket-name-to-ensure-width/trailing-quote-weirdness.bam"‎` (in the error case, we transpose the quote to the beginning: `"gs://...`)
4. if the raw value's filename has a numeric base, do we show the filename and extension correctly? Example: `gs://my-long-bucket-name-to-ensure-width/1298787074140.png` (in the error case, we transpose the file base and extension: `png.1298787074140`)
5. does selecting and copying the value in the cell result in copying the invisible LTR characters?

**Comment by jmthibault79** [comment]
I'm guessing this problem was introduced in UI PR 1267.  Some context on that...

To display initial ellipses we rely on a kluge: render these links as LTR-text.
https://broadinstitute.atlassian.net/browse/GAWB-716
https://github.com/broadinstitute/firecloud-ui/pull/494

This caused a bug where end-punctuation was moved to the beginning:
https://broadinstitute.atlassian.net/browse/GAWB-1912
https://stackoverflow.com/questions/20798667/why-is-a-trailing-punctuation-mark-rendered-at-the-start-with-directionrtl
https://docs.google.com/document/d/1z7OjKLRWgiAufp9A4l4hYtiv6ubQPnA05YOurSaJtFo/edit#heading=h.2qpjd0lz4vv0
https://github.com/broadinstitute/firecloud-ui/pull/1267

**Comment by aednichols** [comment]
@helgridly if you right-click the link and copy, you do not get the extra characters (that must be what we tested...)

**Comment by helgridly** [comment]
Thanks @aednichols , I realised that eventually. But others won't :)

**Comment by irosenbe** [comment]
Decision: Follow-up w/ Saturn on whether they would encounter these errors. Moving forward based on Saturn need due to level of effort involved

**Comment by aednichols** [comment]
Surely if news sites can append "[...] Excerpt copied from blah.com" with Javascript, we can do something similar to truncate some characters.

Or just kill the ellipsis entirely, since it's given us so much grief.
