### ISSUE TITLE
Columns swapped past 1st page of workflow input display

### ISSUE THREAD

**Issue by schaluva** [DataBiosphere/firecloud-app#231]
Under the Monitor tab, within the Workflow Inputs list, if you go past the first page, the Task and Label column values are incorrect in some instances. [Image](https://us.v-cdn.net/5019796/uploads/editor/ob/tb856ja10lc4.png) from user's [post](https://gatkforums.broadinstitute.org/firecloud/discussion/23168/bug-report-listing-of-workflow-input-display-incorrect-after-first-page#latest) shows second page of their workflow inputs where the Task and Label are not correct. 

Additionally, we should show the Task column for subworkflows; currently this is hidden. Since subworkflows can have many tasks, this is a worthwhile column there.

**Comment by davidangb** [comment]
quick code-level triage: I *think* that instead of using `second`  we need the equivalent of `second-to-last` to identify the Task:
https://github.com/broadinstitute/firecloud-ui/blob/develop/src/cljs/main/broadfcui/page/workspace/monitor/workflow_details.cljs#L84
```
:column-data #(second (string/split (key %) #"\."))}]
```
should change to:
```
:column-data #(second (rseq (string/split (key %) #"\.")))}]
```
but I'd like to verify this with someone (comms?) who knows some of our best-practice workflows well and can verify what we *should* be showing in this  table.

**Comment by schaluva** [comment]
I confirmed with the team and the "Label" column should list the variables
listed within the "Task". Therefore, there can be as many duplicate "Task"
rows as there are variables in the task. The "Value" is the value listed in
the method config.

I can get more details if necessary!

**Comment by rebrown1395** [comment]
@irosenbe :)
